#!/bin/bash

./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs1.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs2.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs3.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs4.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs5.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs6.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs7.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs8.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs9.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs10.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs11.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs12.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs13.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs14.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs15.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs16.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs17.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs18.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs19.txt
./RNN20_epochs.py --ignoreColumns=4:6:7:8:5:0:1 --columnOfTags=4 --train=../../data/dimsum-data/dimsum16.train --test=../../data/dimsum-data/dimsum16.test --embeddings=../../data/embeddings/glove.6B.300d.txt,2 > ../results/dimsum/tagsAndDimsum/dimsum20epochs20.txt
